feat: add running row Banner
baza-trainee/donation-baza pull request #35
Opened 2024-09-26 18:03 UTC by oSlavivna

I added a banner and its adaptors. 
I used the button component in the banner. 

The banner has a variable with a string intended for future changes to the phrase by the administrator.
<img width="416" alt="image" src="https://github.com/user-attachments/assets/c1116d00-f231-467c-91aa-6b7de79d86fc">

2024-09-27 01:09 UTC, biryukov-m requested changes
Pull my commits, then:
- Use scss nesting feature among all scss file
- Move banner component to feature/home/bannersection
- Refine map function

2024-09-27 01:09 UTC, biryukov-m commented on src/app/page.tsx
> +import Banner from '@/components/common/Banner/Banner';
move Banner component from common to /features/home/sections/BannerSection/index.tsx

2024-09-27 01:09 UTC, biryukov-m commented on src/components/common/Banner/Banner.module.scss
> +.iconBell {
Use scss nesting
```
.container {
 ...
  .collection {
       ...
  }
  .iconBell {
  ...  
   }
}
```

etc.

2024-09-27 01:09 UTC, biryukov-m commented on src/components/common/Banner/Banner.module.scss
> +.text1 > span {
rename text1 to text

2024-09-27 01:09 UTC, biryukov-m commented on src/components/common/Banner/Banner.module.scss
> +.text1 > span {
use nesting
```
.text {
  & > span {
     ...
  }
}
```

2024-09-27 01:09 UTC, biryukov-m commented on src/components/common/Banner/Banner.module.scss
> +  .text1 {
nesting

2024-09-27 01:09 UTC, biryukov-m commented on src/components/common/Banner/Banner.module.scss
> +  .text1 {
nesting

2024-09-27 01:09 UTC, biryukov-m commented on src/components/common/Banner/Banner.module.scss
> +  .collection {
nesting

2024-09-27 01:09 UTC, biryukov-m commented on src/components/common/Banner/Banner.tsx
> +            .fill(null)
fill with banner var

2024-09-27 01:09 UTC, biryukov-m commented on src/components/common/Banner/Banner.tsx
> +            .map((currentValue, index) => (
```
(text, index) =>

<span key={index}>{text}</span>
```

2024-09-29 19:01 UTC, biryukov-m approved these changes

2024-09-29 19:04 UTC, biryukov-m approved these changes

2024-09-29 19:05 UTC, baza-trainee approved these changes

2024-09-29 19:05 UTC, merged