feat: add help-now-section
baza-trainee/donation-baza pull request #41
Opened 2024-10-02 13:38 UTC by OlhaPo

This PR represents adding help-now section with markup (1440px and larger screens) according to figma design (approved page).

Responsive design will be added in a future update.

![Screenshot_9](https://github.com/user-attachments/assets/3440c0e6-4888-4940-8787-b18f7a5e5fe6)

2024-10-10 10:07 UTC, baza-trainee commented on messages/en.json
> +    "paymentSection": {
rename: HelpNowSection. as component and folder name

2024-10-10 10:42 UTC, biryukov-m requested changes
Change code from requested in comments + 

In helpnow component: 
move non-rendering logic to custom hook in features\home\hooks\use....  
Separate all rendering logic from data logic:
`CURRENCY_VALUES DONATE_SUM DONATE_TYPE handleCurrencyChange handleSumChange handleTypeChange  formatCurrencyLabel ` - move to hook 
`formatCurrencyLabel` move to helpers _features\home\utils\_


And take a look at src/hooks/usePayment hook - example from Ihor.
You can make in two steps: make your own hook, then connect with logic from Ihor's usePayment. Or make in one

2024-10-10 10:42 UTC, biryukov-m commented on messages/en.json
> +    "paymentSection": {
rename: HelpNowSection. as component and folder name

2024-10-10 10:42 UTC, biryukov-m commented on messages/pl.json
> +    "paymentSection": {
rename: HelpNowSection. as component and folder name

2024-10-10 10:42 UTC, biryukov-m commented on messages/ua.json
> +    "paymentSection": {
rename: HelpNowSection. as component and folder name

2024-10-10 10:42 UTC, biryukov-m commented on src/features/home/sections/HelpNowFormSection/HelpNowFormSection.module.scss
rename this file from HelpNowFormSection to HelpNowSection
and rename folder too

2024-10-10 10:42 UTC, biryukov-m commented on src/features/home/sections/HelpNowFormSection/index.tsx
> +  const [selectedType, setSelectedType] = useState(DEFAULT_TYPE);
typescript, for ex.
`useState<CURRENCY>`
`useState<PAYMENT_SUBSCTIPTION>`

2024-10-10 10:42 UTC, biryukov-m commented on src/features/home/sections/HelpNowFormSection/index.tsx
> +      value: 'Щомісячна підписка',
useTranslation

2024-10-10 10:42 UTC, biryukov-m commented on src/features/home/sections/HelpNowFormSection/index.tsx
> +      value: 'Одноразовий платіж',
useTranslation

2024-10-10 12:17 UTC, OlhaPo commented on src/features/home/sections/HelpNowFormSection/index.tsx
> +      default:
Did you mean to do uah in its onw case? Ignore for now that value: string, I'll change it using type

 const formatCurrencyLabel = (value: string) => {
    if (value === 'інша сума') return value;
    switch (selectedCurrency) {
      case 'eur':
        return `${value} euro`;
      case 'zloty':
        return `${value} zł`;
      case 'uah':
        return `${value} грн`;
      default:
        return `${value}`;
    }
  };

2024-10-11 08:52 UTC, biryukov-m commented on src/features/home/sections/HelpNowFormSection/index.tsx
> +      default:
yes

2024-10-11 14:43 UTC, OlhaPo commented on src/features/home/sections/HelpNowFormSection/index.tsx
> +    setSelectedSum(value);
still need to be done

2024-10-14 15:35 UTC, biryukov-m approved these changes

2024-10-16 13:15 UTC, baza-trainee approved these changes

2024-10-16 13:15 UTC, merged