feat: add header and adaptive
baza-trainee/donation-baza pull request #43
Opened 2024-10-03 18:17 UTC by oSlavivna

created headers and adaptives
changed the animation
added logic and operation of the mobile menu 

for now!!! clicking on the mobile menu just closes it, as the links are not yet ready to go to other pages

2024-10-03 22:34 UTC, biryukov-m requested changes
- move navbars, language selectors etc. to separate components with separate styles
- use typescript in languages state
- use more consistant namings for handlers (handleMobileMenuToggle instead of toggleMobileMenu)
- use && operator instead of ternary, where second (right) operand is empty string ''
+ check comments
+ check video
https://www.loom.com/share/f794fee3d815474d8bb0f0b6c905f8de
https://www.loom.com/share/2f05bdd7a03c45a6ab117b043f8bf1fe

2024-10-03 22:34 UTC, biryukov-m commented on src/components/common/Header/index.tsx
> +  const handleLanguageChange = (language: string) => {
change string to type Language

2024-10-03 22:34 UTC, biryukov-m commented on src/components/common/Header/index.tsx
> +          className={`${styles.languageButton} ${isOpen ? styles.noUnderline : ''}`}
use && instead of  `? : ''`

2024-10-07 11:57 UTC, biryukov-m approved these changes

2024-10-09 19:24 UTC, baza-trainee approved these changes

2024-10-09 19:24 UTC, merged