feat: add slider
baza-trainee/donation-baza pull request #51
Opened 2024-10-14 09:07 UTC by oSlavivna

added a slider component.
photos automatically change on the background. 
 
added text adapters. changed the gradient on the background to match the corporate colors

2024-10-14 10:43 UTC, biryukov-m requested changes
- rename and move files (comments)
- use react-slick library
- enable lazy-loading for images
- export from figma .jpeg in x2 resolution

2024-10-14 10:43 UTC, biryukov-m commented on src/components/common/Slider/Slider.module.scss
move this component to  src/features/home/sections/FirstViewSection/components/Slider

2024-10-14 10:43 UTC, biryukov-m commented on src/components/common/Slider/index.tsx
move this component to  src/features/home/sections/FirstViewSection/components/Slider

2024-10-14 10:43 UTC, biryukov-m commented on src/components/common/Slider/Slider.module.scss
rename to ImageSlider

2024-10-14 10:43 UTC, biryukov-m commented on public/img/hero/test1.png
export from figma .jpeg in x2 resolution

2024-10-14 10:43 UTC, biryukov-m commented on public/img/hero/test2.png
reexport

2024-10-17 20:10 UTC, biryukov-m submitted a review, later dismissed

2024-12-05 17:21 UTC, biryukov-m approved these changes

2024-12-09 10:08 UTC, OlhaPo approved these changes

2024-12-09 10:09 UTC, merged