Chore/make faq responsive
baza-trainee/donation-baza pull request #69
Opened 2024-12-11 12:38 UTC by OlhaPo

The following changes, which were not in accordance with the design, were made and require further discussion with frontend team:

1. To prevent images from appearing too small on screens between 1025px and 1240px, set the flex container's layout to flex-direction: column within this range.
![Screenshot_9](https://github.com/user-attachments/assets/38addcd2-c9ac-4088-b996-ca4b9e87ca94)

2. Add an additional breakpoint to optimize image width transitions and prevent it from becoming too narrow or wide on specific screen sizes. 

3. To prevent excessive gaps between columns on larger desktops, apply justify-content: space-evenly starting at the $large-desktop breakpoint

2024-12-12 12:09 UTC, biryukov-m requested changes

2024-12-12 12:09 UTC, biryukov-m commented on .prettierrc
> -  "plugins": ["prettier-plugin-sort-json"],
turn it on

2024-12-12 12:09 UTC, biryukov-m commented on public/img/faq-section.webp
Re-export this from the 1680p design with parameters .jpeg x2. The size will be almost half.
<img width="251" alt="Screenshot 2024-12-12 at 14 04 36" src="https://github.com/user-attachments/assets/a4045017-61b3-4c70-afd6-7be389cb1c4e" />

2024-12-12 12:09 UTC, biryukov-m commented on public/img/faq-section.webp
(saves us space when we will upload this to hosting)

2024-12-12 12:09 UTC, biryukov-m commented on src/features/home/sections/QASection/hooks/useQaData.ts
> +
sort questions here.
This code can help

```suggestion
  // Sort questions by questionNumber in ascending order
  questions.sort((first, second) => {
    // eslint-disable-next-line require-unicode-regexp
    const aNumber = parseInt(first.questionNumber.replace(/\D/g, ''), 10);
    // eslint-disable-next-line require-unicode-regexp
    const bNumber = parseInt(second.questionNumber.replace(/\D/g, ''), 10);
    return aNumber - bNumber;
  });
```

2024-12-17 21:06 UTC, biryukov-m approved these changes

2024-12-17 21:08 UTC, baza-trainee approved these changes

2024-12-18 11:55 UTC, merged